function s = setup
% s = setup returns the settings for run_exp.
%
% % Settings %
%
%   % General
%   s.rng_state    - state of random number generator (not mandatory)
%   s.file_prefix  - prefix for saving files (e.g., analog input recording)
%   s.pause_num    - number of pauses (+ 1 = number of blocks)
%
%   % Scanner trigger
%   s.TR           - repetition time (TR) of MRI sequence in s
%   s.trigger_bit  - bit reflecting hardware pin with MRI trigger input
%   s.trigger_max  - number of triggers to wait after start of scanner
%
%   % Stimuli   
%   s.stim_types   - stimulus typ labels (0 - none; 1 - near)
%   s.stim_types_num - number of stimulus types (should be a multiple of s.stim_steps)
%   s.near_d       - detection probability for stimulus s.stim_types(2)
%   s.near_name    - name for stimulus intensity in dialog
%   s.stim_steps   - intensity steps as factors of near- and supra-threshold intensity
%   % s.stim_p_steps - perfomance level steps in relation to s.near_p and s.supra_p
%   s.pulse_t      - duration of stimuls (rectangular pulse) in ms
%   s.wave_t       - duration of waveform with rectangular pulse in ms
%   s.stim_dec     - number of decimal digits of intensity in mA (doc dlg_intensities)
%   s.stim_max     - maximum possible stimulus intensity in mA
%   s.TTL_t        - TTL pulse length (1 ms)
%   s.TTL_V        - TTL pulse amplitude (5 V)
% 
%   % Trial
%   s.get_flip_i	- number of samples for initial flip interval estimation with Screen('GetFlipInterval')
%   s.trigger2fix  - duration of scanner trigger to fixation cross onset in s
%   s.fix_t        - duration of fixation cross in s
%   s.cue_t        - duration of stimulus cue in s
%   s.stim_delay   - min/max vector for pseudo-randomized stimulus delay in s
%   s.stim2resp    - pause between stimulus cue and response screen in s
%   s.resp_window  - 'variable'/'fixed' - stop/continue after first button press
%   s.resp1_max_t  - maximum response time 1 in s
%   s.resp2_max_t  - maximum response time 2 in s
%   s.resp_p_min_t - minimum time left to show response pause screen in s
%   s.ITI          - inter trial interval (ITI) in s
%
%   % Screen design
%   s.window_color - screen background rgb color vector
% 
%   % Text
%   s.txt_color    - text rgb color vector
%   s.txt_font     - font type
%   s.txt_size     - font size for response screens
%   s.cue_size     - font size for fix, cue and pause screens
% 
%   % Messages
%   s.fix          - fixation symbol (e.g., '+')
%   s.cue          - stimulus cue symbol (e.g., '~+~')
%   s.resp1_txt    - yes/no response text options, yes-no-order important, e.g. ['J'; 'N']
%   s.resp2_txt    - confidence response text options
%   s.resp1_offset - 1st response text offset left from screen center
%   s.ITI_cue      - inter trial interval symbol
%   s.pause_msg    - message on pause screen
%   s.scanner_msg  - prompt to start scanner
% 
%   % Buttons
%   s.lpt_adr1     - parallel port address (see device manager - LPT1 details - resources)
%   s.lpt_adr2     - as above but 'I/O Range' #2
%   s.lpt_dir      - parallel port direction ('bi' or 'uni')
%   s.btn_resp1    - button codes for yes/no response
%   s.btn_resp2    - button codes for confidence response
%   s.btn_esc      - button code for quiting experiment
%
%   % Instruction
%   s.instr_dir    - instruction directory with condition subdirectories
%                     (relative to directory of nt_exp.m)
%   s.instr_subdir_wildcard    - instruction subdirectory wildcard
%   s.instr_img_wildcard       - filename wildcard of instruction image files
%
%
% Author:           Martin Grund
% Last update:      October 20, 2016

%% Settings

%% General
% s.rng_state = sum(100*clock); % If not defined, generated by run_exp
s.file_prefix = 'CCSomato_';
s.blocks = 3;

%% Scanner trigger
s.TR = 0.750;
s.trigger_bit = 7;
s.trigger_max = 1;

%% Stimuli
s.stim_types = [0 1];
s.stim_types_num = [20 100];
s.near_d = .45;
s.near_name = 'Near-threshold';
s.stim_steps = 1; % [.95 1 1.05];
s.pulse_t = 0.2; % = psi.pulse_t [IMPORTANT FOR DT9812, see exp1 for bug]
s.wave_t = 10; % = psi.wave_t [IMPORTANT FOR DT9812, see exp1 for bug]
s.stim_dec = 2;
s.stim_max = 5;

s.TTL_t = 1;
s.TTL_V = 5;

%% Trial
s.get_flip_i = 200;
s.trigger2fix = 0.100;
s.fix_t = 1.000;
s.cue_t = 2.000;
s.stim_delay = [0.1 1.9];
%s.stim2resp = 9.000;
s.resp_window = 'variable';
s.resp1_max_t = 2.000;
%s.resp2_max_t = 1.500;
s.resp_p_min_t = 0.300;
%s.ITI = 7.000;

%% Screen design
s.window_color = [200 200 200];%[250 250 250]; % grey98 (very light grey)

%% Text
s.txt_color = [40 40 40]; % grey15-16 (anthracite)
s.txt_font = 'Arial';
s.txt_size = 30;
s.cue_size = 50;

%% Messages
s.fix = '+';
s.cue = '~+~';
s.resp1_txt = ['J'; 'N'];
%s.resp2_txt = ['1'; '2'; '3'; '4'];
s.resp1_offset = 75;
s.ITI_cue = '+';
s.pause_msg = '# Pause #\n\n\nWeiter mit beliebiger Taste';
s.scanner_msg = 'Start scanner';

%% Buttons
s.lpt_adr1 = '3FF8';% '378';
s.lpt_adr2 = '3FF4';% hex2dec(psi.lpt_adr1) + 1024
s.lpt_dir = 'bi';
s.btn_resp1 = [2 3];
%s.btn_resp2 = [1 2 3 4];
s.btn_esc = 5;

%% Instruction
s.instr_dir = '/instr/';
s.instr_subdir_wildcard = 'condition_*';
s.instr_img_wildcard = '*instruction*.png';